### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by magdesign** [pierrep/lpmt#2]
Just a contribution for the readme:

**Install instructions**
cd into `/OF/addons/` folder and install following addons:

git clone https://github.com/danomatika/ofxMidi.git
git clone https://github.com/YCAMInterlab/ofxTimecode.git
git clone https://github.com/arturoc/ofxTween.git

on your system also install gobjc++ :
`sudo apt-get install gobjc++`

cd into `/OF/apps` folder and execute:
`git clone https://github.com/pierrep/lpmt.git`

cd into `lpmt` folder and build with:
`make`

**Comment by pierrep** [comment]
Thanks for prodding me to upgrade the readme. The `sudo apt-get install gobjc++` requirement is odd, I don't remember needing that. Didn't install_dependencies.sh from the OF scripts resolve that for you?

**Comment by magdesign** [comment]
Nope, it does not seem to, however, its not a big deal, bigger problem is that it does not compile (see other issue)....

**Comment by pierrep** [comment]
Ok I'll have a look and try and write up clear install instructions. I
added a few Add-ons locally to the repo because of the difficulty of
compiling stuff. Currently I have it running happily on Ubuntu 18.04 and
PopOs 19.10

**Comment by pierrep** [comment]
Ok I've included ofxTween and ofxTimecode into this project as they are getting old and don't seem to be changing. This will make things easier. I've included some basic instruction as well.
