### ISSUE TITLE
Gui error

### ISSUE THREAD

**Issue by wangwenfeng0** [pierrep/lpmt#4]
When I compile the source code, it will produce an access rights conflict in the xtree file, the function name is
 "template<class _Other>
_Nodeptr _Lbound(const _Other& _Keyval) const
{	// find leftmost node not less than _Keyval
		_Nodeptr _Wherenode = this->_Get_data()._Myhead;	// end() if search fails
		_Nodeptr _Pnode = _Wherenode->_Parent;
}
"
the error information is :
_Wherenode is nullpter
![image](https://user-images.githubusercontent.com/16935291/77226329-75a01e80-6bb2-11ea-8285-6cbf85c66663.png)
![image](https://user-images.githubusercontent.com/16935291/77226340-8a7cb200-6bb2-11ea-8188-17442f421c60.png)

When I remove the gui source codes, it will be no error.
How could I fix this problem, thank you very much.

**Comment by pierrep** [comment]
What platform and compiler are you seeing this on? You may have set up your
build environment incorrectly

**Comment by wangwenfeng0** [comment]
I use the Windows 10 system with openframeworks 0.11.0, and the compiler is VS2017. I have tracked the error in the code, when in the ofxSimpleGuiConfig.cpp to run the ttf.load("data/type/Roboto-Regular.ttf", 9); it will produce the error.
![image](https://user-images.githubusercontent.com/16935291/77227429-46da7600-6bbb-11ea-8235-da92cd704364.png)
![image](https://user-images.githubusercontent.com/16935291/77227441-696c8f00-6bbb-11ea-893b-104223c08f6e.png)
![image](https://user-images.githubusercontent.com/16935291/77227506-ba7c8300-6bbb-11ea-875e-ceaf33ac5a6e.png)

I find the fonts_table size is zero, thank you for your reply, I will try to fix it.

**Comment by pierrep** [comment]
Interesting, thanks for debugging. I'll compile it in Windows (I'm using a similar setup, vs2017, OF 0.11.0, Windows 10) and see if I can reproduce it.

**Comment by pierrep** [comment]
You can work around it for the moment by changing the code to this:
```
    /* set up font */
    bUseFont = false;
//    ttf.load("data/type/Roboto-Regular.ttf", 9);
```

**Comment by pierrep** [comment]
Can you get the latest code? It should be fixed.

**Comment by wangwenfeng0** [comment]
OK, I will test it,  It should be fixed with your work, thank you.
