### ISSUE TITLE
compilation pb : fatal error: ofxMostPixelsEver.h

### ISSUE THREAD

**Issue by proximcreation** [pierrep/lpmt#5]
Hey,

I’m stuck at compilation state with a :
fatal error: ofxMostPixelsEver.h: Aucun fichier ou dossier de ce type
 #include "ofxMostPixelsEver.h"

Is there an appimage or something precompiled somwhere ?
thanks :)

**Comment by pierrep** [comment]
Hi,
What code are you running? The master branch doesn't even have a reference to that header file, it's commented out.

The plan is to eventually package it via an AppImage on Linux, and I've had a shot at it already, but failed. OpenFrameworks has LOADS of dependencies, so it's not trivial. I think it's possible though, I just need some dedicated time on the problem.
